### PR TITLE
Add nats default port

### PR DESCRIPTION
**Pull request by ronakbanka**

### CODE REVIEW

**Comment by ronakbanka** [comment]
@jmtuley Hey John can you review this PR ?

**Comment by ajackson** [comment]
Hi @ronakbanka 

We can't accept pull requests without a CLA.   Have you signed one?   If you have can you publish this per the instructions above.  It will speed up accepting pull requests in the future.  Thanks.

**Comment by ronakbanka** [comment]
Hi @ajackson 

yes we have already signed CLA  from Org Rakuten . Thanks

**Comment by erikjasiak** [comment]
Hi Ronak,
   Apologies for the delay - can you point to where you had another pull request come through against CF?  Do you have an option to publish membership in the cloudfoundry.org project?

   I'll also cc your profile email on a connection to the foundation.

Thanks,
Erik

**Comment by erikjasiak** [comment]
Loggregator anchor Rohit is exploring one issue we've had with merge/promote before inserting this.   Story is up-to-date
https://www.pivotaltracker.com/story/show/98256094

Erik

**Comment by ronakbanka** [comment]
Thanks @erikjasiak

**Pull request merged**
