### PR TITLE
Add write deadline for websocket connection to avoid long hang

### PR DESCRIPTION
**Pull request by chenziliang**
When there is a slow Firehose client, the `ws.WriteMessage` will block there for a long time until client drain the messages and there is free space for the write.

By design, TrafficaController will close the message channel in 5 seconds if the Firehose client slow. But this `ws.WriteMessage` may hang out there for a long time for a slow client which results in "the 5 seconds time out" doesn't take effective as expect.

The PR is setting up a write deadline so if WriteMessage timed out, we basically does a clean shutdown for that websocket

### CODE REVIEW

**Comment by bradylove** [comment]
@chenziliang Does this fix the other issue you filed (#295)?

**Comment by chenziliang** [comment]
@bradylove No. Only the indefinitely timeout issue.

**Comment by apoydence** [comment]
@chenziliang Why 6 seconds? I'm sure that is not arbitrary time.

**Comment by chenziliang** [comment]
@apoydence A good one. The backpressure of the events chan is 5 seconds: if client can't drain one message in the chan on websocket server side, server disconnects the client. Picking 6 seconds is making sure the write will not time out before the chan backpressure time out.

**Comment by JohannaSmith** [comment]
Looks good to me. Merging.

**Pull request merged**
