### PR TITLE
Move syslog daemon config

### PR DESCRIPTION
**Pull request by enocom**
The syslog daemon config is not loggregator source code and as such has
no business in code.cloudfoundry.org/loggregator. This commit moves it
up as a top level entry in Bosh's src directory.

This commit also updates the configuration of Metron and Metron Windows
to ensure that both jobs consume a syslog daemon config package as part
of their configuration. Subsequent Metron package and job configuration
remains the same.

### CODE REVIEW

**Comment by enocom** [comment]
I would appreciate someone double-checking the code here to make sure I've not made a mistake moving the various pieces.

**Comment by bradylove** [comment]
@enocom 

We attempted to deploy this to a bosh lite however encountered the following error while creating the bosh release:
```
bosh create-release --force
Building a release from directory '/home/pivotal/workspace/loggregator':
  - Constructing packages from directory:
      - Reading package from '/home/pivotal/workspace/loggregator/packages/metron_agent_windows':
          Collecting package files:
            Missing files for pattern 'loggregator/src/code.cloudfoundry.org/loggregator/metron/syslog_daemon_config/*'
  - Constructing jobs from manifest:
      - Expected to find package 'loggregator_common' since it's a dependency of job 'doppler'
      - Expected to find package 'golang1.8.3' since it's a dependency of job 'loggregator-acceptance-tests'
      - Expected to find package 'loggregator_common' since it's a dependency of job 'loggregator_trafficcontroller'
      - Expected to find package 'loggregator_common' since it's a dependency of job 'metron_agent'
      - Expected to find package 'syslog_daemon_config' since it's a dependency of job 'metron_agent_windows'
      - Expected to find package 'reverse_log_proxy' since it's a dependency of job 'reverse_log_proxy'
      - Expected to find package 'loggregator_common' since it's a dependency of job 'syslog_drain_binder'

Exit code 1
```

**Comment by enocom** [comment]
@bradylove I've update the PR and tested that I can create a bosh release. Will you double check that this is correct?

**Comment by apoydence** [comment]
@enocom I tried again to deploy these changes however metron fails to start:

I was able to get better logging by doing the following on the consul VM:

```
consul/bfad811f-5152-40de-84ea-c7423102ccc6:/var/vcap/jobs/metron_agent/bin# ./metron_agent_ctl start
metron: no process found
metron: no process found
metron: no process found
metron: no process found
./metron_agent_ctl: line 25: /var/vcap/packages/metron_agent/syslog_daemon_config/setup_syslog_forwarder.sh: No such file or directory
```

**Comment by enocom** [comment]
@apoydence Thanks for trying again. I'm going to close this PR and will open a new PR once I've sorted out these problems.

**Pull request closed without merging**
