### PR TITLE
instance_id needs to be a string, not a number

### PR DESCRIPTION
**Pull request by jandubois**
see https://github.com/cloudfoundry/loggregator/commit/bbe02f9

A corresponding change also needs to happen to https://github.com/cloudfoundry/dea_logging_agent/blob/933055098700f18d61dcedfaa8a1aee796ae1f58/jobs/dea_logging_agent/templates/dea_logging_agent.json.erb#L6

### CODE REVIEW

**Comment by jandubois** [comment]
> A corresponding change also needs to happen to https://github.com/cloudfoundry/dea_logging_agent/blob/933055098700f18d61dcedfaa8a1aee796ae1f58/jobs/dea_logging_agent/templates/dea_logging_agent.json.erb#L6

Actually, it doesn't.  This change is only needed when the file is written using `JSON.pretty_generate`.

**Comment by ahevenor** [comment]
@jandubois is there a particular issue this is causing? We'd like to know steps to test this before it is scheduled. 

Thanks
Adam

**Comment by jandubois** [comment]
Yes, the generated json files are read by Go code that used to expect a `uint` and now expects a `string` and will now die if `instance_id` is set via `spec.index` instead of `spec.id`. This is fallback code that was introduced when the type was changed, but obviously it was never tested.

Just look at the commit that introduced this change, it should make the problem obvious:

https://github.com/cloudfoundry/loggregator/commit/bbe02f9b737dfa5246868f0c87d81c8f89f37438#diff-1aa966246a81a2f186fa24a3af07a69dL53

Not sure how you would test this; maybe deploy with a version of BOSH that doesn't have`spec.id`? 

I ran into this when deploying CF on docker using https://github.com/hpcloud/fissile, but that will be non-trivial to set up if you are not using it otherwise.

**Comment by jandubois** [comment]
Actually, it is a little bit more subtle: In the original commit linked above the code was correct because the JSON was written with explicit quotes:

```
  "Index": "<%= instance_id %>",
```

But https://github.com/cloudfoundry/loggregator/commit/a25edbb321a205426cd0da5cf553ccf389ffbf87 switched to using

```
<%= JSON.pretty_generate(args) %>
```

And now the value will no longer be quoted unless it is a string type. And if it isn't quoted then the Go JSON deserializer will detect a type-mismatch and die.

**Comment by apoydence** [comment]
I pulled the changes and ran the LATs. They passed so I'm going to merge this in.

**Pull request merged**
