### PR TITLE
Add metron_agent.etcd.machines to spec and jobs json

### PR DESCRIPTION
**Pull request by andrew-edgar**
Required for Diego to pickup the etcd release from MEGA

Diego Story : https://www.pivotaltracker.com/story/show/101226166
MEGA Story : https://www.pivotaltracker.com/story/show/99848706

Signed-off-by: Luan Santos <lsantos@pivotal.io>

### CODE REVIEW

**Comment by ematpl** [comment]
@erikjasiak: Any chance we could get some evaluation of this change soon? This property separation is blocking those linked stories to have Diego use MEGA's etcd-release instead of the separately maintained job in diego-release. Thanks!

cc @Amit-PivotalLabs

**Comment by roxtar** [comment]
@ematpl @erikjasiak is on vacation. Tagging @ajackson for prioritization.

**Comment by ematpl** [comment]
@roxtar Sounds reasonable to me, but we should have validation from the Diego pair that worked on this.

**Comment by jfmyers9** [comment]
@roxtar,

The etcd-release that we intend to use for diego depends on the `etcd.machines` property. However, currently we also have metron in diego which also depends on the `etcd.machines` property. The big issue here is that we want to use different etcd clusters for different jobs. To generalize this, we have each of the jobs in our release declare their own `<job-name>.etcd.machines` instead of a global `diego.etcd.machines`. This prevents property collisions between jobs from separate releases. In this case, `loggregator.etcd.machines` is totally reasonable.

The team that will actually care about setting patterns and standards in this case would be MEGA, for us, all we need is to get rid of the collision. It would be a good idea to check in with them before moving forward. @Amit-PivotalLabs, @jpalermo: Thoughts or feelings?

Thanks,
@jfmyers9 && @luan, CF Diego

**Comment by Amit-PivotalLabs** [comment]
@jfmyers9 @roxtar LGTM :+1: 

I think switching from `metron_agent.etcd.machines` to `loggregator.etcd.machines` is okay, both solve the problem.  I'm not sure I have a strong opinion between the two.

**Comment by ematpl** [comment]
@roxtar @Jim-Campbell Just to be clear, the Diego team is fine with whatever namespace you choose for these properties, and it sounds like MEGA needs you to adopt a namespace anyway as part of the multiple-releases plan for decomposing cf-release. We're also fine if you want to take the PR and make whatever changes you deem appropriate on top of it, but if you're expecting the Diego or MEGA teams to do that instead, please let us know!

Thanks,
Eric

**Comment by fraenkel** [comment]
Code has been lifted and applied.

**Pull request closed without merging**
