### PR TITLE
Organize Metron using app-internal structure

### PR DESCRIPTION
**Pull request by enocom**
- Remove duplicate LICENSE and NOTICE which are available at the top
level of loggregator
- Remove unused tools/metronbenchmark which wrote into metron using the UDP API

### CODE REVIEW

**Comment by jasonkeene** [comment]
Did you use `gomvpkg`? I'm using it for doppler. It works well but is very slow, at least running it inside a container.

**Comment by enocom** [comment]
Yes, I did use `gomvpkg`. It did a beautiful job with the source code, but failed to update the paths in test files. Otherwise, I'm very glad to know about it.

**Comment by jasonkeene** [comment]
Yea, I had the problem with test files as well. Sad.

**Comment by jasonkeene** [comment]
@enocom This failed in integration tests because of a build error: https://loggregator.ci.cf-app.com/teams/main/pipelines/loggregator/jobs/run-tests/builds/262

I am going to revert it. I now realize you will get twice the additions and deletions. I hope this wasn't intentional on your part! Please run the full test suite locally, build errors should be caught locally.

**Comment by enocom** [comment]
@jasonkeene The integration suite continues to surprise me with the way it reaches into various private internals. All the same, it's my mistake. The build errors are caused by two monitor tests, which do not merit integration tests. I'll make the necessary changes and double check the build before making another PR.

**Pull request merged**
