### PR TITLE
updated template file for syslog_drain_binder to allow BulkApiUsernam…

### PR DESCRIPTION
**Pull request by Nino-K**
…e value to come form cc

### CODE REVIEW

**Comment by jmtuley** [comment]
Hi @Nino-K !

Thanks for submitting this. Technically, I have no problem merging your request; it's definitely a deficiency today and you've found a nice and simple solution.

 However, as dreddbot noted above, Legal requires us not to merge PRs until you've submitted a CLA. I'd love to get this merged as soon as you've taken care of that.

**Comment by Nino-K** [comment]
Hi John,

Thanks for your email. I believe we (ActiveState) have a corporate CLA with
Cloud Foundry foundation and my name should be on the list.

My full name and Github Id is listed below:

Full name: Nino Khodabandeh
Github Id: nino-k

Cheers,
Nino

**Comment by erikjasiak** [comment]
+Chip

Hi Nino - did you happen to publish your membership per the cfdreddbot
email?  I recall ActiveState has signed the agreement; it's the org
publishing dreddbot is looking for.  If you don't see an option to publish,
let me know that too (why I added Chip.)

<snip>
If you are confident that you're covered under a Corporate CLA, please make
sure you've publicized your membership in the appropriate Github Org, per these
instructions
<https://help.github.com/articles/publicizing-or-concealing-organization-membership/>
.
</snip>

Thanks,
Erik

**Comment by Nino-K** [comment]
Hi Erik,

My membership happened to be private and I just made it public. Thanks for
pointing that out.

Cheers,
Nino

**Pull request merged**
