### PR TITLE
RLP and TC ctl scripts kill process before starting

### LINKED ISSUE #285: ReverseLogProxy does not ensure a process is already running
Doppler and Metron both try to kill any Dopplers and Metrons before starting. This ensures the start won't have a port collision. However the ReverseLogProxy does not guard from this.

### PR DESCRIPTION
**Pull request by bradylove**
When starting RLP we want to ensure there is not already a running instance of the RLP.

Also fixed indentation of CTL script.

Fixes #285.

### CODE REVIEW

**Comment by bradylove** [comment]
This still needs to be verified with a bosh deploy and a monit stop/start while a RLP is running.

**Comment by bradylove** [comment]
Updated to also include fix for #284.

**Comment by bradylove** [comment]
Also need to verify this is working for TC with bosh deploy + monit stop/start.

**Comment by apoydence** [comment]
I deployed this to a bosh-lite and did:

```
bosh -e lite -d loggregator restart log-api
bosh -e lite -d loggregator restart reverse_log_proxy
```

I also went onto both VMs and messed with the pid file and restarted the process. It stopped the old process and started the new one.

**Pull request merged**
