### PR TITLE
Doppler firehose should listen on all adapters

### PR DESCRIPTION
**Pull request by fraenkel**
- A co-located nozzle should be able to connect via the loopback adapter

### CODE REVIEW

**Comment by jasonkeene** [comment]
We were discussing allowing the user to specify what interfaces to bind to via a config option. Alot of daemons do this and allow the value `0.0.0.0` and `::` to bind to all IPv4 and IPv6 interfaces. Some examples:

- `listen_addresses` config option with postgres: http://www.postgresql.org/docs/9.1/static/runtime-config-connection.html#GUC-LISTEN-ADDRESSES
- `ListenAddress` config option with openssh: http://www.tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap15sec122.html

**Comment by wfernandes** [comment]
@fraenkel Let us know if @jasonkeene's suggestion sounds good to you. We can either do it ourselves or you could update the PR.

Thanks.

**Comment by fraenkel** [comment]
@wfernandes @jasonkeene What is it that you are trying to solve?
Can you show me how someone would specify the correct adapter for your BOSH release on each instance of your Doppler?

**Comment by wfernandes** [comment]
@fraenkel The intent is to specify via a config property the interface to listen on instead of listening to all interfaces. So instead of binding to `:config.OutgoingPort`, we'd listen on `config.ListenAddress:config.OutgoingPort`.

We were thinking that listening on all interfaces might be a security concern and we prefer locking it down to specified interfaces.

We'll talk with Jim about this. If he's ok with this, we'll merge it in.

**Comment by wfernandes** [comment]
@fraenkel Just spoke with Alex and Jim. They said they were ok with listening to all interfaces.

**Pull request merged**
