### PR TITLE
Enables forwarding container metrics to syslog drain

### PR DESCRIPTION
**Pull request by msaliminia**
Fixes https://github.com/cloudfoundry/loggregator/issues/150

This change enables doppler to forward container metrics to syslog drain.

### CODE REVIEW

**Comment by ahevenor** [comment]
@msaliminia we have decided this is not a good trajectory for Loggregator but we are curious about your use case. Alternatively you should be able to get what you need from the firehose syslog nozzle - see https://github.com/cloudfoundry-community/firehose-to-syslog-boshrelease

**Comment by msaliminia** [comment]
Why we need it:
Our customers want to have container metrics and logs in one place for monitoring, alerting and also correlation of log messages like errors with metrics. 

Problem with firehose API:
The firehose API is for operators and administrators only and doesn't work with normal non-admin credentials, we can't share our CF admin credentials with customers.

Why syslog sink:
- There is already a syslog sink forwarder available in doppler.
- Easy to use for customers. They don't need to bind any extra service for that.
- Easy to manage the app lifecycle. If you fetch the metrics from client side, you need to manage at least one fetcher/connection per app and it is hard to manage app's lifecycle from client-side. You need to handle the cases like what happens if the app goes down, is stopped or deleted.

**Comment by ahevenor** [comment]
@mariash and @CAFxX we are researching ways to support this in https://www.pivotaltracker.com/story/show/135231265 for this and issue #150

**Comment by ahevenor** [comment]
@CAFxX and @msaliminia we have some changes that will scale out syslog seperately and strategically we'd like to seperate metrics and logs rather than combine them. Logs and metrics have different delivery needs hence our thinking here.

**Comment by davebotelho** [comment]
Can you tell me what happened to this request?  We also have customers that would like to see the container metrics in the syslog drain for monitoring and alerting through alternative methods like ELK or Splunk?

**Pull request closed without merging**
