### PR TITLE
Fix Truncating Buffer race condition bug

### PR DESCRIPTION
**Pull request by momchil-sap**
Fixes a race condition in Doppler as described in #105.

It replaces the current `TruncatingBuffer` logic of swapping the output channel with an implementation that drains the channel when blocked. This fixes the race condition, improves readability, and avoids some unnecessary `sync.Mutex` usage.

### CODE REVIEW

**Comment by momchil-sap** [comment]
Seems I missed some of the tests when running `ginkgo -r` locally. Will fix them and update Pull Request.

**Comment by momchil-sap** [comment]
@Amit-PivotalLabs ,

The pull request should now be done. This should fix #105, we discussed. I would appreciate it if someone had a look.

Initially, it had some mistakes that were mostly due to my lack of understanding of the code and how to properly run the whole test suite. 

All unit and integration tests now run successfully on my local machine, though some tests that are not truncating_buffer/doppler related are unstable at times. I built a doppler executable and ran it manually on bosh-lite, just to be sure, and the issue does not occur.

I have force-squashed some of my commits into a more clean commit history, as the pull request contained a lot of "Fix <something>" commits at one point.

I am not able to get a CI build to trigger. Is this because of the commit squash or because you are going through a CI change (last week it was Travis, this week it seems to be Concourse)? Is there a way to manually tigger this?

Regards,
Momchil Atanassov

**Comment by Jim-Campbell** [comment]
+warren, Loggregator anchor

We've got it queued up in our backlog
<https://www.pivotaltracker.com/n/projects/993188>. We'll look at it when
we pull it. Thanks!

On Tue, Mar 8, 2016 at 8:25 AM, Momchil Atanassov <notifications@github.com>
wrote:

> @Amit-PivotalLabs <https://github.com/Amit-PivotalLabs> ,
>
> The pull request should now be done. This should fix #105
> <https://github.com/cloudfoundry/loggregator/issues/105>, we discussed. I
> would appreciate it if someone had a look.
>
> Initially, it had some mistakes that were mostly due to my lack of
> understanding of the code and how to properly run the whole test suite.
>
> All unit and integration tests now run successfully on my local machine,
> though some tests that are not truncating_buffer/doppler related are
> unstable at times. I built a doppler executable and ran it manually on
> bosh-lite, just to be sure, and the issue does not occur.
>
> I have force-squashed some of my commits into a more clean commit history,
> as the pull request contained a lot of "Fix " commits at one point.
>
> I am not able to get a CI build to trigger. Is this because of the commit
> squash or because you are going through a CI change (last week it was
> Travis, this week it seems to be Concourse)? Is there a way to manually
> tigger this?
>
> Regards,
> Momchil Atanassov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry/loggregator/pull/106#issuecomment-193823321>
> .
>



-- 
Jim Campbell | Product Manager | Cloud Foundry | Pivotal.io | 303.618.0963

**Comment by wfernandes** [comment]
We manually merged this PR. See e9c507b5839f51c266c0eadcc3f3a7df02391ea2

Thanks for your contribution @momchil-sap :)

(@wfernandes and @nelsam)

**Pull request closed without merging**
